NYT article
patrick-angelos/Patrick-Saima pull request #1
Opened 2020-11-25 13:00 UTC by patrick-angelos

Project 1 pull request

2020-11-25 15:34 UTC, MuriloRoque commented
## Status: Invalid 🔴 

### Hello @patrick-angelos and @saimaAnis21 👋 

### Guys, first of all, welcome to Microverse! 😄 

### I just need you to be a little bit more descriptive in this project, please edit your Pull Request description and add more details about the project (technologies and techniques used to build it, what the webpage is about, etc.). Currently, the description is too short and tells us very little about the project.

Kindly make the requested changes and submit for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-25 17:39 UTC, arslanbisharat requested changes
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [ ] You have two HTML files with the same content please delete one.
 

- [ ] IDs shouldn't be used in selectors because these rules are too tightly coupled with the HTML and have no possibility of reuse. It's much preferred to use classes in selectors and then apply a class to an element in the page.

### Readme

- [ ] Please have a look at the suggestions by me on your readme. 

### Navbar

- [ ] Please add more height to your navbar. On the Original page, there is more height present on the page but in your clone, text, links, and logo are not present at the correct position because of less height of the navbar. 

**Clone**

![chrome-capture](https://user-images.githubusercontent.com/58504655/100259501-188f1080-2f6a-11eb-8f4f-85267b0c69b8.jpg)

**Original**

![chrome-capture (1)](https://user-images.githubusercontent.com/58504655/100259565-2a70b380-2f6a-11eb-97e4-9b5cfdbd1fea.jpg)


- [ ] There should a "Hamburger button", a search icon and a link with text on the leftmost side present as present On the original page. But that is missing in your clone.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

**Clone**

![chrome-capture (2)](https://user-images.githubusercontent.com/58504655/100259969-b08cfa00-2f6a-11eb-97af-aeee25452126.jpg)

- [ ] The NY Times logo should be a link but in your clone, it is only an image. 

- [ ] Login and Subscribe button should align correctly on the navbar. These buttons should also have the same color as present on the original page. 

**Clone**

![chrome-capture](https://user-images.githubusercontent.com/58504655/100260654-78d28200-2f6b-11eb-82ba-9372f74046c0.jpg)

**Original**
![chrome-capture (1)](https://user-images.githubusercontent.com/58504655/100260674-812abd00-2f6b-11eb-9f61-9a877fd18c4d.jpg)
### Main

- [ ] Please use the same font for the page as present in the design. 

- [ ] You are missing this section from your webpage. 

**Original**

![chrome-capture (3)](https://user-images.githubusercontent.com/58504655/100260872-c9e27600-2f6b-11eb-9509-616c028a2912.jpg)

- [ ] Please add a proper description in the Editor's pick section and decrease the gap between content. 

**Clone**

![chrome-capture (4)](https://user-images.githubusercontent.com/58504655/100261047-044c1300-2f6c-11eb-9224-2e90993c2a08.jpg)

**Original**

![chrome-capture (5)](https://user-images.githubusercontent.com/58504655/100261188-33fb1b00-2f6c-11eb-965a-ac9fc9b1c699.jpg)

##### Bottom part

- [ ] It should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) but that is missing in your project. Please work on it. 
- [ ] It should contain links to more popular articles on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) but that is missing in your project. Please work on it



**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-11-25 17:39 UTC, arslanbisharat commented on README.md
> +> Replication of a NYT article.
- [ ] Please add a screenshot of your project here. This will help you to show your project professionally.

2020-11-25 17:39 UTC, arslanbisharat commented on README.md
> +https://patrick-angelos.github.io/Patrick-Saima/
- [ ] [Optional] You can embed this link in one or two words like **Live link** or **Demo Link**

2020-11-25 17:39 UTC, arslanbisharat commented on README.md
> +Git clone git@github.com:patrick-angelos/Patrick-Saima.git <your local Git Directory>
- [ ] Add a heading like **Clone**

2020-11-25 17:39 UTC, arslanbisharat commented on README.md
> +
- [ ] Please add more social links here. This will help you to make your repo more professional and descriptive.

2020-11-25 17:39 UTC, arslanbisharat commented on article.html
> +        <a href="">SPACE & COSMOS</a>
- [ ] Please remove link styling, change font-family, and weight too. This will help you to make it like the original one.

2020-11-25 17:39 UTC, arslanbisharat commented on article.html
> +            <button>LOG IN</button>
- [ ] Please give proper styling and alignment. This will help you to make it like the original one.

2020-11-25 17:39 UTC, arslanbisharat commented on article.html
> +        <img src="icons/nyt.png" alt="New York Times">
- [ ] Make it a link. This will help you to make it like the original one.

2020-11-25 17:39 UTC, arslanbisharat commented on article.html
> +        </p>
- [ ] enclose these sections into a single main stage. This is called a semantic tag.

2020-11-25 17:39 UTC, arslanbisharat commented on article.html
> +</footer>
- [ ] [Optional] Please use a single footer here. You can then use the nested footer if you want them.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#main_img {
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#footer1 {
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#footer2 {
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#footer2 a {
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#grid_content {
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +  background-size: 100%;
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#Inflation p {
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#super_jumbo {
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#soc_flex button {
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#soc_flex {
- [ ] Please don't use Id as a selector.

2020-11-25 17:39 UTC, arslanbisharat commented on styles.css
> +#soc_flex div {
- [ ] Please don't use Id as a selector.

2020-11-26 13:30 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @patrick-angelo and @saimaAnis21 , I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

- [ ] Use similar font and font style with the original website.
<img width="455" alt="fonts" src="https://user-images.githubusercontent.com/38358081/100356158-e6ca8800-3003-11eb-9a02-f4923d572b72.png">
<img width="383" alt="fonts original" src="https://user-images.githubusercontent.com/38358081/100356319-1aa5ad80-3004-11eb-920c-1ba1143f873a.png">

- [ ] Give space between the article title and header
<img width="677" alt="title" src="https://user-images.githubusercontent.com/38358081/100356378-33ae5e80-3004-11eb-819c-a2498bce3c37.png">

- [ ] Fix the footer style; it should look like the original footer
<img width="1439" alt="footer original" src="https://user-images.githubusercontent.com/38358081/100356609-82f48f00-3004-11eb-83b1-7adc42cd1c85.png">
<img width="1438" alt="footer" src="https://user-images.githubusercontent.com/38358081/100356631-8b4cca00-3004-11eb-9838-049e5058b510.png">

- [ ] Don't repeat CSS rules create common utility classes for common CSS rules. E.g. 
```
.flex {
display: flex;
}
```

[OPTIONAL] 

- [ ] Add a fixed footer (it sticks to the bottom part of the screen)
![sticky footer](https://user-images.githubusercontent.com/38358081/100356680-9bfd4000-3004-11eb-8a26-d631481be54c.png)


Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-11-27 11:27 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @patrick-angelos 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Add the description for `href` attribute.
- [ ] Update the footer as previous TSE explained. (see the [image](https://user-images.githubusercontent.com/29689273/100444494-5789a700-30cd-11eb-874e-531aa328e355.png))

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-11-27 11:27 UTC, umairarshadbutt commented on index.html
> +            <a href=""><img src="icons/hum-icon.png" alt="humberger icon"></a>
Add the description in `href` attribute

2020-11-27 11:27 UTC, umairarshadbutt commented on index.html
> +            <a class = "no_deco space" href="">SPACE & COSMOS</a>
Add the description in `href` attribute

2020-11-27 11:27 UTC, umairarshadbutt commented on index.html
> +        <a href=""><img src="icons/nyt.png" alt="New York Times"></a>
Add the description in `href` attribute

2020-11-27 11:47 UTC, saimaAnis21 commented
@umairarshadbutt 
Hi Umair, in your review you have asked us to change the footer as pointed out by the previous TSE. If you notice the previous TSE has attached a screenshot of the original footer which is not the same as you have pointed out in your link of the footer.

2020-11-27 12:13 UTC, umairarshadbutt commented
Hi @saimaAnis21 
There is one sticky footer(Which one is asked by precious TSE) and the second one is that which I have attached.

2020-11-27 15:04 UTC, arslanbisharat requested changes
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**


- [ ] Please add proper icons instead of images for the hamburger and search icon. And make them clickable. Please have a look at the original page. 

![chrome-capture (3)](https://user-images.githubusercontent.com/58504655/100461793-143e3100-30eb-11eb-84c0-86b90aa36605.jpg)

- [ ] Subscribe Now and Login is actual buttons on the navbar. SO make them clickable too. 

- [ ] Increase the font-size of **Space Ripples Reveal Big Bang's Smoking Gun**. 

- [ ] Add more space between these links and remove side space. same with the footer. 

![chrome-capture (4)](https://user-images.githubusercontent.com/58504655/100462031-7139e700-30eb-11eb-9df6-f79ea2640f57.jpg)

- [ ] As described earlier, Please make NYT logo a link in the footer too. 

- [ ] 

**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-11-27 15:53 UTC, arslanbisharat approved these changes
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:

_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-11-27 18:31 UTC, abredi reviewed
### Status: Invalid  ↩️
Hi @patrick-angelos and @saimaAnis21, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏 You did well on this project. I appreciate your efforts to achieve this milestone 🦍. 
But, this project is already approved, so you don't have to create a review request to Microverse. Instead, you can ask your friends or colleagues to review your code.

Don't forget to merge with the master branch.

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Connect me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-12-09 12:16 UTC, merged